[package]
name = "hello_enum"
version = "0.1.0"
authors = ["jinxin0821 <jinxin.0821@bytedance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
