[package]
name = "hello_panic"
version = "0.1.0"
authors = ["jinxin0112 <m18508218948@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
